Add template.md
Enactus-UFRGS/enactus-team-management-rfcs pull request #1
Opened 2018-06-17 21:36 UTC by guitassinari

2018-06-18 18:39 UTC, LigiaBatista commented
Nice!!

2018-06-19 01:55 UTC, daviolrb commented
So, let's do it

2018-06-19 17:06 UTC, MelissaFil commented
Desculpa a demora. É pra comentar em ingres ? rs

2018-06-19 17:27 UTC, MelissaFil commented on 0000-template.md
> +# Basic example
A primeira que eu omito rs

2018-06-19 21:45 UTC, daviolrb approved these changes
So far so good 💃

2018-06-19 21:56 UTC, daviolrb approved these changes
Here we go

2018-06-20 01:39 UTC, LigiaBatista requested changes
improve it, please!!

2018-06-20 01:41 UTC, LigiaBatista requested changes
improve it !!

2018-06-20 02:44 UTC, merged